version: '3'

services:
    api:
        build:
            context: .
            dockerfile: docker/api/Dockerfile
        ports:
            - "81:80"
    
    webapp:
        build:
          context: .
          dockerfile: docker/webapp/Dockerfile
        ports:
            - "82:80"